theme file change to theme package
vivliostyle/docs.vivliostyle.org pull request #10
Opened 2020-08-31 16:15 UTC by ogwata

theme file change to theme package

2020-08-31 17:15 UTC, MurakamiShinyu requested changes

2020-08-31 17:15 UTC, MurakamiShinyu commented on create-book.md
> +A theme package is a CSS file that defines the style of the book. Please refer to A specification below.
"A theme package is a CSS file" の "is" を "contains" に変更、
日本語のほうも、「CSSファイルです」を「CSSファイルを含みます」に変更するとよいと思います。

2020-09-02 08:20 UTC, ogwata commented on create-book.md
> +A theme package is a CSS file that defines the style of the book. Please refer to A specification below.
修正しました。ご確認を。

2020-09-02 08:45 UTC, MurakamiShinyu approved these changes

2020-09-02 09:14 UTC, merged